export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const BALANCE_REQUESTED = 'BALANCE_REQUESTED';
export const BALANCE_SUCCEEDED = 'BALANCE_SUCCEEDED';
export const BALANCE_FAILED = 'BALANCE_FAILED';

export const TRANSFER_REQUESTED = 'TRANSFER_REQUESTED';
export const TRANSFER_SUCCEEDED = 'TRANSFER_SUCCEEDED';
export const TRANSFER_FAILED = 'TRANSFER_FAILED';
